document.addEventListener('DOMContentLoaded', () => {
  let introAnimation = document.querySelector('.introAnimation')
  let firstLetter = document.querySelector('.firstLetter')
  let secondLetter = document.querySelector('.secondLetter')
  let jTop = document.querySelector('#jTop')
  let jMid = document.querySelector('#jMid')
  let jBot = document.querySelector('#jBot')
  let cTop = document.querySelector('#cTop')
  let cMid = document.querySelector('#cMid')
  let cBot = document.querySelector('#cBot')

  introAnimation.classList.add('active')
  firstLetter.classList.add('active')
  secondLetter.classList.add('active')
  jTop.classList.add('active')
  jMid.classList.add('active')
  jBot.classList.add('active')
  cTop.classList.add('active')
  cMid.classList.add('active')
  cBot.classList.add('active')

  setTimeout(() => {
    introAnimation.classList.remove('active')
    introAnimation.style.display = 'none'
    firstLetter.classList.remove('active')
    secondLetter.classList.remove('active')
    jTop.classList.remove('active')
    jMid.classList.remove('active')
    jBot.classList.remove('active')
    cTop.classList.remove('active')
    cMid.classList.remove('active')
    cBot.classList.remove('active')
  }, 6000)
})
